# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_data = pd.read_csv("../WeatherPy/Weather_Data.csv")
weather_data.head()

,City,Country,City Number,Temperature,Humidity,Latitude,Longtitude,Clouds,Wind Speed,Max Temperature
0,Grindavik,IS,3416888,48.2,93,63.84,-22.43,90,9.17,48.2
1,Tasiilaq,GL,3424607,44.6,83,65.61,-37.64,75,27.51,44.6
2,Francistown,BW,933778,60.8,51,-21.17,27.51,0,9.17,60.8
3,Longyearbyen,SJ,2729907,44.6,56,78.22,15.64,75,5.82,44.6
4,Barrow,US,5880054,39.2,86,71.29,-156.79,90,3.36,39.2

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps with API key
gmaps.configure(api_key=g_key)


#Create variables
locations = weather_data[['Latitude', 'Longtitude']]
humidity = weather_data["Humidity"]

#Creating heat layer
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity = 200,
                                 point_radius = 5)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
weather_data.head()

,City,Country,City Number,Temperature,Humidity,Latitude,Longtitude,Clouds,Wind Speed,Max Temperature
0,Grindavik,IS,3416888,48.2,93,63.84,-22.43,90,9.17,48.2
1,Tasiilaq,GL,3424607,44.6,83,65.61,-37.64,75,27.51,44.6
2,Francistown,BW,933778,60.8,51,-21.17,27.51,0,9.17,60.8
3,Longyearbyen,SJ,2729907,44.6,56,78.22,15.64,75,5.82,44.6
4,Barrow,US,5880054,39.2,86,71.29,-156.79,90,3.36,39.2

In [5]:
#Ideal Weather Vacation Parameters
ideal_weather = weather_data[weather_data['Max Temperature']>= 80]
ideal_weather = ideal_weather[weather_data['Max Temperature']<= 90]
ideal_weather = ideal_weather[weather_data['Clouds'] <= 50]
ideal_weather = ideal_weather[weather_data['Wind Speed'] < 9]

ideal_weather

C:\Users\kledesma\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\kledesma\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.
C:\Users\kledesma\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """

,City,Country,City Number,Temperature,Humidity,Latitude,Longtitude,Clouds,Wind Speed,Max Temperature
21,Constantine,DZ,2501152,84.20,35,36.37,6.61,20,6.93,84.20
46,Butaritari,KI,2110227,82.08,74,3.07,172.79,28,7.47,82.08
53,Tianpeng,CN,1792916,82.74,65,30.99,103.94,40,4.47,86.00
56,Hithadhoo,MV,1282256,84.36,64,-0.60,73.08,0,2.30,84.36
72,Ingham,US,4997130,84.99,42,42.60,-84.38,1,8.05,87.01
79,Saint George,US,5546220,84.58,10,37.10,-113.58,1,4.70,87.01
86,Baghdad,IQ,98182,89.60,24,33.34,44.40,0,3.36,89.60
95,Hilo,US,5855927,76.95,65,19.73,-155.09,40,5.82,82.40
109,Pedernales,DO,3495137,87.24,57,18.04,-71.74,7,7.58,87.24
119,Teluknaga,ID,1990589,78.80,83,-6.10,106.64,40,4.70,80.01
121,Iaciara,BR,3461641,82.44,34,-14.10,-46.63,4,2.57,82.44
126,George Town,MY,1735106,82.20,88,5.41,100.34,20,2.24,82.40
175,Siraha,NP,1282770,84.43,67,26.65,86.21,31,5.50,84.43
178,Pleasanton,US,5383777,89.47,19,37.66,-121.87,1,6.93,90.00
179,Grottaglie,IT,3175773,83.57,49,40.54,17.43,0,3.02,84.99
186,Algiers,DZ,2507480,86.00,48,36.75,3.04,20,5.82,86.00
197,Makakilo City,US,5850554,81.48,61,21.35,-158.09,20,6.93,82.40
228,Alugan,PH,1731248,80.20,79,12.22,125.48,36,2.57,80.20
229,Laguna,US,5364271,88.48,27,38.42,-121.42,1,5.82,90.00
230,Port Dickson,MY,1734815,80.31,83,2.52,101.80,20,3.36,80.60
241,Teahupoo,PF,4033543,80.60,57,-17.83,-149.27,20,3.36,80.60
252,Polignano a Mare,IT,6537556,82.22,100,41.00,17.22,0,5.12,84.99
262,Cassilândia,BR,3466750,80.73,45,-19.11,-51.73,49,8.12,80.73
266,Impruneta,IT,3175528,78.04,42,43.69,11.25,0,6.93,80.60
302,Topaowan,CN,1811829,80.01,94,30.67,112.69,1,2.01,80.01
319,Macas,EC,3654541,80.60,51,-2.32,-78.12,40,6.93,80.60
329,Guangzhou,CN,1809858,85.17,70,23.12,113.25,40,4.47,86.00
333,Pratāpgarh,IN,1259338,83.77,61,24.03,74.78,0,6.96,83.77
336,Bilma,NE,2446796,86.94,12,18.69,12.92,0,3.51,86.94
339,Pulsano,IT,3169760,83.41,54,40.38,17.36,0,1.99,84.99
349,Kulhudhuffushi,MV,1337613,82.65,79,6.62,73.07,40,7.70,82.65
354,Oriximiná,BR,3393471,84.47,77,-1.77,-55.87,29,3.62,84.47
356,Carutapera,BR,3402648,80.92,78,-1.20,-46.02,0,6.87,80.92
406,Papar,MY,1733353,80.20,88,5.73,115.93,20,4.70,80.60
439,Ukiah,US,5404476,85.73,25,39.15,-123.21,1,8.19,86.00
440,Thinadhoo,MV,1337610,84.49,62,0.53,72.93,12,3.09,84.49
490,Rurrenabaque,BO,3906209,86.41,53,-14.44,-67.53,8,6.64,86.41
501,Thessalon,CA,6164831,86.00,30,46.25,-83.57,1,4.70,86.00
526,West Lafayette,US,4928096,84.69,58,40.43,-86.91,40,4.70,87.80
528,Seydi,TM,1218420,80.04,16,39.48,62.91,0,8.30,80.04
539,Tiarei,PF,4033356,80.60,57,-17.53,-149.33,20,3.36,80.60
546,Muros,ES,3115824,74.17,67,42.78,-9.06,7,5.99,81.00

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
hotel_df = ideal_weather
hotel_df["Hotel Name"] = ''
hotel_df["Hotel Lat"] = ''
hotel_df["Hotel Long"] = ''

hotel_df.head()

,City,Country,City Number,Temperature,Humidity,Latitude,Longtitude,Clouds,Wind Speed,Max Temperature,Hotel Name,Hotel Lat,Hotel Long
21,Constantine,DZ,2501152,84.20,35,36.37,6.61,20,6.93,84.20,,,
46,Butaritari,KI,2110227,82.08,74,3.07,172.79,28,7.47,82.08,,,
53,Tianpeng,CN,1792916,82.74,65,30.99,103.94,40,4.47,86.00,,,
56,Hithadhoo,MV,1282256,84.36,64,-0.60,73.08,0,2.30,84.36,,,
72,Ingham,US,4997130,84.99,42,42.60,-84.38,1,8.05,87.01,,,

In [7]:
params = {"radius" : 5000,
         "type" : "lodging",
         "keyword" : "Hotel",
         "key" : g_key}

for index, row in hotel_df.iterrows():
    try:
        base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
        latitude = row["Latitude"]
        longtitude = row["Longtitude"]
    
        params["location"] = f"{latitude},{longtitude}"
    
        response = requests.get(base_url, params=params).json()
        
        #Getting Hotel Name
        hotel_df.loc[index, "Hotel Name"] = response['results'][1]['name']
        
        #Re-formatting and inserting hotel address
        hotel_lat = response['results'][1]['geometry']['location']['lat']
        hotel_long = response['results'][1]['geometry']['location']['lng']
        hotel_df.loc[index, "Hotel Lat"] = hotel_lat
        hotel_df.loc[index, "Hotel Long"] = hotel_long
        hotel_df.loc[index, "Hotel Address"] = hotel_address
        hotel_df.loc[index, "Hotel Address"] = hotel_address
    except:
        pass

In [8]:
#Removing cities that didn't successfully pull in a hotel
hotel_df['Hotel Name'].replace('',np.nan,inplace=True)
hotel_df = hotel_df[hotel_df['Hotel Name'].notna()]
hotel_df

,City,Country,City Number,Temperature,Humidity,Latitude,Longtitude,Clouds,Wind Speed,Max Temperature,Hotel Name,Hotel Lat,Hotel Long
21,Constantine,DZ,2501152,84.20,35,36.37,6.61,20,6.93,84.20,Protea Hotel by Marriott Constantine,36.3572,6.60909
53,Tianpeng,CN,1792916,82.74,65,30.99,103.94,40,4.47,86.00,Ibis Hotel,30.9887,103.952
56,Hithadhoo,MV,1282256,84.36,64,-0.60,73.08,0,2.30,84.36,Abuharee Grand,-0.59966,73.0815
79,Saint George,US,5546220,84.58,10,37.10,-113.58,1,4.70,87.01,Hilton Garden Inn St. George,37.0785,-113.583
86,Baghdad,IQ,98182,89.60,24,33.34,44.40,0,3.36,89.60,Rukn Kahramana Baghdad,33.3115,44.4254
95,Hilo,US,5855927,76.95,65,19.73,-155.09,40,5.82,82.40,Reeds Bay Resort Hotel,19.7279,-155.063
109,Pedernales,DO,3495137,87.24,57,18.04,-71.74,7,7.58,87.24,Hotel Pedernales Italia,18.0417,-71.7427
119,Teluknaga,ID,1990589,78.80,83,-6.10,106.64,40,4.70,80.01,FM7 Resort Hotel Jakarta Airport,-6.10696,106.685
121,Iaciara,BR,3461641,82.44,34,-14.10,-46.63,4,2.57,82.44,Hotel Mineiro,-14.1062,-46.6337
126,George Town,MY,1735106,82.20,88,5.41,100.34,20,2.24,82.40,"Eastern & Oriental Hotel, Penang",5.42317,100.336
178,Pleasanton,US,5383777,89.47,19,37.66,-121.87,1,6.93,90.00,Aloft Dublin-Pleasanton,37.7036,-121.865
179,Grottaglie,IT,3175773,83.57,49,40.54,17.43,0,3.02,84.99,Masseria Le Lamie,40.5476,17.4667
186,Algiers,DZ,2507480,86.00,48,36.75,3.04,20,5.82,86.00,Hotel El Djezair,36.7544,3.04621
197,Makakilo City,US,5850554,81.48,61,21.35,-158.09,20,6.93,82.40,Marriott's Ko Olina Beach Club,21.3318,-158.121
228,Alugan,PH,1731248,80.20,79,12.22,125.48,36,2.57,80.20,Pasyadahan Beach Resort,12.1763,125.48
229,Laguna,US,5364271,88.48,27,38.42,-121.42,1,5.82,90.00,Holiday Inn Express & Suites Elk Grove Central...,38.4241,-121.399
230,Port Dickson,MY,1734815,80.31,83,2.52,101.80,20,3.36,80.60,Avillion Admiral Cove,2.47711,101.846
241,Teahupoo,PF,4033543,80.60,57,-17.83,-149.27,20,3.36,80.60,Pension Bonjouir,-17.8656,-149.222
252,Polignano a Mare,IT,6537556,82.22,100,41.00,17.22,0,5.12,84.99,Grotta Palazzese,40.9959,17.2211
262,Cassilândia,BR,3466750,80.73,45,-19.11,-51.73,49,8.12,80.73,Hotel Esplanada,-19.1206,-51.7237
266,Impruneta,IT,3175528,78.04,42,43.69,11.25,0,6.93,80.60,RELAIS VILLA IL SASSO,43.73,11.2979
319,Macas,EC,3654541,80.60,51,-2.32,-78.12,40,6.93,80.60,Casa Independiente en el Campo,-2.34674,-78.1473
329,Guangzhou,CN,1809858,85.17,70,23.12,113.25,40,4.47,86.00,DoubleTree by Hilton Hotel Guangzhou,23.1313,113.271
333,Pratāpgarh,IN,1259338,83.77,61,24.03,74.78,0,6.96,83.77,Hotel Padmavati,24.036,74.7807
339,Pulsano,IT,3169760,83.41,54,40.38,17.36,0,1.99,84.99,HOTEL Eden Park,40.3469,17.3822
354,Oriximiná,BR,3393471,84.47,77,-1.77,-55.87,29,3.62,84.47,Castanheira Hotel,-1.77106,-55.8634
406,Papar,MY,1733353,80.20,88,5.73,115.93,20,4.70,80.60,Uncle Ho Motel,5.72865,115.934
439,Ukiah,US,5404476,85.73,25,39.15,-123.21,1,8.19,86.00,Comfort Inn & Suites,39.1322,-123.2
490,Rurrenabaque,BO,3906209,86.41,53,-14.44,-67.53,8,6.64,86.41,Hotel Ambaibo,-14.4426,-67.5279
526,West Lafayette,US,4928096,84.69,58,40.43,-86.91,40,4.70,87.80,Hampton Inn & Suites West Lafayette,40.4198,-86.9012
546,Muros,ES,3115824,74.17,67,42.78,-9.06,7,5.99,81.00,A Casa da Fonte,42.7781,-9.06054

In [9]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
citylist = hotel_df["City"].tolist()
countrylist = hotel_df["Country"].tolist()
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Hotel Lat", "Hotel Long"]]

In [10]:
# Add marker layer ontop of heat map
fig = gmaps.figure()
markers = gmaps.marker_layer(locations,
    info_box_content=[f"Name: {city}" for city in citylist])



fig.add_layer(markers)
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))